version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
       - postgres-data:/var/lib/postgresql/data
  api:
    container_name: api
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/puck-api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-data: {}