---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: air-rockey-api
  labels: 
    app: api
spec:
  ports:
    - port: 5432
  selector:
    app: api
    tier: database
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres
  namespace: air-rockey-api
  labels:
    app: api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api
      tier: database
  template:
    metadata:
      name: postgres
      labels:
        app: api
        tier: database
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "api-secrets"
              key: "db-user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "api-secrets"
              key: "db-user-pass"
        - name: POSTGRES_DB
          value: "puck_api_development"
        ports:
        - containerPort: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: air-rockey-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi