# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= (ENV['POSTGRES_HOST'] || 'localhost') %>
  timeout: <%= (ENV['DB_TIMEOUT'] || '5000').to_i %>
  username: <%= (ENV['POSTGRES_USER'] || 'postgres') %>
  password: <%= (ENV['POSTGRES_PASSWORD'] || 'postgres') %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: puck_api_development

test:
  <<: *default
  database: puck_api_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: puck_api_production
